### PR TITLE
fix: Fix duplicated service names in metrics metadata

### LINKED ISSUE #186: Metrics service dimension contains duplicated names
Version: `v1.12.1-sumo-2`

In some circumstances, the metrics sent in to Sumo have duplicated service names in the `service` dimension. An example of duplicated `service` metadata:

> basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-headless_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_basic-redis-master_payment-gateway-redis-headless_payment-gateway-redis-headless_payment-gateway-redis-master_payment-gateway-redis-master

After deduplication, this goes down to `basic-redis-headless_basic-redis-master_payment-gateway-redis-headless_payment-gateway-redis-master`.

### PR DESCRIPTION
**Pull request by astencel-sumo**
Fixes #186

### CODE REVIEW

**Review by pmalek-sumo — COMMENTED** [review]
tests 😿 ?

**Comment by astencel-sumo** [comment]
> tests 😿 ?

Added tests, thanks for reminding me! 💡

**Review by pmalek-sumo — COMMENTED** [review]
I'm cool with this PR, the only nit I have is to add a short description under which circumstances it did happen before your fix here. 

I presume when there were more than 1 endpoint for a pod/service?

**Comment by astencel-sumo** [comment]
> I'm cool with this PR, the only nit I have is to add a short description under which circumstances it did happen before your fix here.
> 
> I presume when there were more than 1 endpoint for a pod/service?

Yeah I thought about this. Maybe I should create an issue describing the circumstances and link the PR to it?

**Review by perk-sumo — APPROVED** [review]

**Review by pmalek-sumo — APPROVED** [review]

**Pull request merged**
