### PR TITLE
Config to disable metadata refresh selectively

### PR DESCRIPTION
**Pull request by gizmo-rt**

### CODE REVIEW

**Comment by sumo-drosiek** [comment]
Hi @gizmo-rt,
Thank you for the contribution. Could you add unit tests for the change?

**Review by swiatekm-sumo — CHANGES_REQUESTED** [review]
The change itself looks fine to me. Can you fix the existing test and add one for the new functionality?

**Review by sumo-drosiek — APPROVED** [review]

**Review by swiatekm-sumo — APPROVED** [review]
LGTM

**Comment by astencel-sumo** [comment]
Looks good, would be good to mention the added configuration option in the README.

**Comment by gizmo-rt** [comment]
> Looks good, would be good to mention the added configuration option in the README.
> 
> Also I wouldn't mind adding a `log.debug` message that mentions the key is deleted without refresh.
> 
> @gizmo-rt

@astencel-sumo Added log and updated readme

**Comment by astencel-sumo** [comment]
> > Looks good, would be good to mention the added configuration option in the README.
> > Also I wouldn't mind adding a `log.debug` message that mentions the key is deleted without refresh.
> > @gizmo-rt
> 
> @astencel-sumo Added log and updated readme

Great, thanks a lot!

**Review by astencel-sumo — APPROVED** [review]

**Pull request merged**
